### PR TITLE
Automate safe rolling restarts for workflow workers (graceful shutdown + Docker/Compose fixes)

### LINKED ISSUE #1289: Automate safe rolling restarts of workflow workers after CI-CD deploys
For my workflow workers, I need it to automatically update whenever we push a new update to the code. So we have CI-CD workflows through GitHub that automatically update our running processes. So I also need the workflow workers to also automatically run, and automatically to safely shut down when the new CI-CD process that finishes, so that it doesn't interrupt any existing workflows. For it to restart once it's finished all of its existing workflows. So I don't know if we need to update the GitHub workflows file, or if we need to dockerize it. We can explore both options.

### PR DESCRIPTION
**Pull request by youngchingjui**
Summary
- Adds graceful shutdown to the workflow workers so CI/CD restarts don’t interrupt in-flight jobs
- Corrects the workflow-workers Dockerfile to build the correct package
- Updates docker-compose worker service to use the workflow-workers image and to stop gracefully (SIGTERM + stop_grace_period)

What changed
1) Graceful shutdown in apps/workers/workflow-workers/src/index.ts
   - Listens to SIGTERM/SIGINT
   - Calls worker.close() to stop fetching new jobs and wait for current job to finish
   - Closes QueueEvents and Redis connections
   - Supports configurable timeout via SHUTDOWN_TIMEOUT_MS (default 30s) and forces exit if exceeded
   - Handles unhandledRejection/uncaughtException with logging and graceful shutdown attempt

2) Dockerfile fixes for workflow-workers
   - apps/workers/workflow-workers/Dockerfile now targets the @issue-to-pr/workflow-workers package (previously was filtering @issue-to-pr/worker)
   - Uses STOPSIGNAL SIGTERM and runs pnpm start for the correct filter

3) Docker Compose worker service
   - docker/compose/worker.yml now points to apps/workers/workflow-workers/Dockerfile
   - Adds stop_signal: SIGTERM and stop_grace_period: 60s to give the worker time to finish jobs during container stop/redeploy

Why this solves the issue
- During CI/CD deploys (or container restarts), the process now receives SIGTERM and will:
  - stop taking new jobs immediately
  - finish the in-flight job safely
  - exit cleanly so a new instance can start
- Docker/Compose are aligned with the workflow-workers package so deploys rebuild the correct image and respect graceful stop semantics.

Notes for Operations
- If you are running the worker under systemd instead of Docker, systemctl restart sends SIGTERM by default. With this change, the worker exits gracefully as well. You can optionally export SHUTDOWN_TIMEOUT_MS to control the max wait before force-exit.
- If using docker compose, apply the updated compose/worker.yml and run:
  docker compose build worker && docker compose up -d worker
  to trigger a rebuild and a rolling-style restart of the worker container.

Validation
- Repository lint/check scripts pass (next lint, prettier --check, tsc --noEmit)
- No behavioral changes to job processing except improved lifecycle management.

Follow-ups (optional)
- Consider adding a healthcheck endpoint or liveness/readiness signals if you plan to run multiple replicas behind an orchestrator like ECS/Kubernetes for true rolling updates.
- Consider enabling multiple replicas and a queue-based canary/rolling strategy if needed for zero downtime scale out.

Closes #1289

## Summary by CodeRabbit

* **Bug Fixes**
  * Added graceful shutdown for the worker to reduce interrupted jobs and improve stability during restarts and deployments.
  * Improved handling of unexpected errors to prevent abrupt exits.

* **Chores**
  * Updated container build and runtime configuration to target the correct worker service.
  * Set SIGTERM as the stop signal with an extended grace period for orderly shutdowns.
  * Adjusted startup command and production artifacts to align with the updated worker service.

### CODE REVIEW

File: apps/workers/workflow-workers/src/index.ts [hunk 1]
```diff
@@ -72,3 +72,54 @@ queueEvents.on("failed", ({ jobId, failedReason, prev }) => {
     `Job event ${jobId} has failed with reason ${failedReason}; previous status was ${prev}`
   )
 })
+
+// Graceful shutdown handling: stop taking new jobs, wait for in-flight jobs to finish, then exit.
+const SHUTDOWN_TIMEOUT_MS = Number(process.env.SHUTDOWN_TIMEOUT_MS ?? 30000)
+let shuttingDown = false
+
+async function gracefulShutdown(signal: NodeJS.Signals) {
```
Comment (youngchingjui) [inline apps/workers/workflow-workers/src/index.ts:80]: ideally we put this function in helper.ts file

File: apps/workers/workflow-workers/src/index.ts [hunk 2]
```diff
@@ -72,3 +72,54 @@ queueEvents.on("failed", ({ jobId, failedReason, prev }) => {
...
+    // Ensure connections are dropped before forcing exit
+    try {
+      connection.disconnect()
+    } catch {}
+    process.exit(1)
+  }, SHUTDOWN_TIMEOUT_MS)
+
+  try {
+    // Close the worker: this stops fetching new jobs and waits for the current one to finish
+    await worker.close()
```
Comment (youngchingjui) [inline apps/workers/workflow-workers/src/index.ts:98]: if we move this function to another file, can we import worker, queueEvents, connection, and would these .close() / .quit() commands still work in the objects passed in?

File: docker/compose/worker.yml [hunk 3]
```diff
@@ -1,16 +1,19 @@
...
-      dockerfile: apps/workers/Dockerfile
+      dockerfile: apps/workers/workflow-workers/Dockerfile
     environment:
       - NODE_ENV=production
       - REDIS_URL=redis://redis:6379
     env_file:
       - ${ENV_FILE}
+    # Give the worker time to finish in-flight jobs before stopping
+    stop_signal: SIGTERM
+    stop_grace_period: 60s
```
Comment (youngchingjui) [inline docker/compose/worker.yml:13]: Again, 60s is too short for some workflows. We need to increase this to 1 hour.
